import { StyleSheet } from 'react-native';
import COLORS from '../config/colors';

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.background, paddingTop: 50, paddingHorizontal: 20 },
  containerCentrado: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.background,
  },
  textoCarregando: { marginTop: 10, fontSize: 16, color: COLORS.onSurfaceVariant, fontWeight: '500' },

  // Header
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: COLORS.surface,
    paddingVertical: 12,
    marginHorizontal: -20,
    paddingHorizontal: 20,
    marginBottom: 18,
  },
  headerLeft: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  headerIconButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: COLORS.surfaceContainerHigh,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerIconText: { fontSize: 22, color: COLORS.primary, fontWeight: '700' },
  headerTitulo: { fontSize: 20, fontWeight: '700', color: COLORS.primary },
  headerAvatar: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: COLORS.surfaceContainerHigh,
    borderWidth: 2,
    borderColor: COLORS.primaryContainer,
    justifyContent: 'center',
    alignItems: 'center',
  },

  // Painel principal
  tituloPainel: { fontSize: 22, fontWeight: '700', color: COLORS.onSurface },
  subtituloPainel: { fontSize: 14, color: COLORS.onSurfaceVariant, marginTop: 2, marginBottom: 16 },

  inputBusca: {
    height: 46,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: COLORS.outlineVariant,
    backgroundColor: COLORS.surfaceContainerLow,
    paddingHorizontal: 16,
    fontSize: 15,
    color: COLORS.onSurface,
  },

  filtroPillsContainer: {
    flexDirection: 'row',
    backgroundColor: COLORS.surfaceContainer,
    borderRadius: 14,
    padding: 4,
    marginTop: 14,
    marginBottom: 18,
  },
  filtroPill: { flex: 1, paddingVertical: 9, borderRadius: 11, alignItems: 'center' },
  filtroPillAtivo: { backgroundColor: COLORS.primaryContainer },
  filtroPillTexto: { fontSize: 13, fontWeight: '700', color: COLORS.onSurfaceVariant },
  filtroPillTextoAtivo: { color: COLORS.onPrimaryContainer },

  colunaMesas: { gap: 14 },

  // Badge de status
  badge: { paddingHorizontal: 12, paddingVertical: 5, borderRadius: 999 },
  badgeOcupada: { backgroundColor: COLORS.errorContainer },
  badgeLivre: { backgroundColor: COLORS.tertiaryContainer },
  badgeTexto: { fontSize: 12, fontWeight: '700' },
  badgeTextoOcupada: { color: COLORS.onErrorContainer },
  badgeTextoLivre: { color: COLORS.onTertiaryContainer },

  // Card de mesa (lista)
  cardMesa: {
    flex: 1,
    backgroundColor: COLORS.surfaceContainerLowest,
    borderRadius: 16,
    padding: 16,
    borderTopWidth: 4,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
  },
  cardMesaBordaOcupada: { borderTopColor: COLORS.error },
  cardMesaBordaLivre: { borderTopColor: COLORS.tertiaryContainer },
  cardMesaTopo: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
  cardMesaDivider: { height: 1, backgroundColor: COLORS.outlineVariant, marginVertical: 10 },
  labelMesa: { fontSize: 13, fontWeight: '700', color: COLORS.onSurfaceVariant },
  numeroMesaGrande: { fontSize: 34, fontWeight: '800', color: COLORS.onSurface, marginTop: 2 },
  linhaCardMesa: { flexDirection: 'row', justifyContent: 'space-between' },
  linhaCardMesaLabel: { fontSize: 13, color: COLORS.onSurfaceVariant },
  linhaCardMesaValor: { fontSize: 15, fontWeight: '700', color: COLORS.primary },
  cardMesaHint: { fontSize: 13, color: COLORS.onSurfaceVariant },
  cardMesaHintMuted: { fontSize: 12, color: COLORS.onSurfaceVariant, opacity: 0.8 },

  // Tela de mesa livre
  telaLivreWrapper: { flex: 1, justifyContent: 'center' },
  boxMesaLivre: {
    backgroundColor: COLORS.surfaceContainerLowest,
    padding: 28,
    borderRadius: 20,
    alignItems: 'center',
    elevation: 2,
  },
  iconeMesaLivreCirculo: {
    width: 76,
    height: 76,
    borderRadius: 38,
    backgroundColor: COLORS.surfaceContainerHigh,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  tituloMesaLivre: { fontSize: 19, fontWeight: '700', color: COLORS.onSurface, textAlign: 'center' },
  infoTexto: { fontSize: 14, color: COLORS.onSurfaceVariant, textAlign: 'center', marginTop: 8, marginBottom: 22 },
  botaoPrimario: {
    backgroundColor: COLORS.primaryContainer,
    width: '100%',
    paddingVertical: 15,
    borderRadius: 14,
    alignItems: 'center',
  },
  textoBotaoPrimario: { color: COLORS.onPrimaryContainer, fontSize: 16, fontWeight: '700' },

  // Detalhes da mesa - bento
  scrollDetalhes: { flex: 1 },
  bentoWrapper: { gap: 14, marginBottom: 22 },
  cardInfoMesa: {
    backgroundColor: COLORS.surfaceContainerLowest,
    borderRadius: 16,
    padding: 18,
    borderTopWidth: 4,
    borderTopColor: COLORS.error,
    elevation: 2,
  },
  cardInfoMesaTopo: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
  linhaInfoMesa: { marginTop: 10 },
  linhaInfoMesaTexto: { fontSize: 13, color: COLORS.onSurfaceVariant },
  cardTotalComanda: {
    backgroundColor: COLORS.primaryContainer,
    borderRadius: 16,
    padding: 20,
  },
  labelTotalComanda: {
    fontSize: 12,
    fontWeight: '700',
    color: COLORS.onPrimaryContainer,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 6,
  },
  valorTotalComanda: { fontSize: 38, fontWeight: '800', color: COLORS.onPrimaryContainer },
  qtdItensTexto: { fontSize: 14, color: COLORS.onPrimaryContainer, opacity: 0.85, marginTop: 6 },

  // Menu rápido
  secaoMenuRapido: { marginBottom: 22 },
  secaoMenuRapidoTopo: { marginBottom: 10 },
  tituloSecao: { fontSize: 17, fontWeight: '700', color: COLORS.onSurface },
  cardMenuRapido: {
    backgroundColor: COLORS.surfaceContainerLowest,
    borderRadius: 16,
    padding: 14,
    alignItems: 'center',
    width: 110,
    marginRight: 12,
    elevation: 1,
  },
  iconeMenuRapidoCirculo: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: COLORS.surfaceContainerHigh,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  nomeMenuRapido: { fontSize: 12.5, fontWeight: '700', color: COLORS.onSurface, textAlign: 'center' },
  precoMenuRapido: { fontSize: 12.5, color: COLORS.primary, fontWeight: '700', marginTop: 4 },

  // Histórico
  secaoHistorico: { marginBottom: 10 },
  boxHistorico: {
    backgroundColor: COLORS.surfaceContainerLowest,
    borderRadius: 16,
    marginTop: 12,
    borderWidth: 1,
    borderColor: COLORS.outlineVariant,
    overflow: 'hidden',
  },
  linhaHistorico: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 14,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.outlineVariant,
  },
  linhaHistoricoSemBorda: { borderBottomWidth: 0 },
  linhaHistoricoEsquerda: { flexDirection: 'row', alignItems: 'center', gap: 12, flex: 1 },
  iconeHistoricoCirculo: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: COLORS.surfaceContainerHigh,
    justifyContent: 'center',
    alignItems: 'center',
  },
  nomeItemHistorico: { fontSize: 15, color: COLORS.onSurface, fontWeight: '500', flexShrink: 1 },
  linhaHistoricoDireita: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  qtdBadge: { backgroundColor: COLORS.surfaceContainerHighest, paddingHorizontal: 8, paddingVertical: 3, borderRadius: 6 },
  qtdBadgeTexto: { fontSize: 12.5, fontWeight: '700', color: COLORS.onSurfaceVariant },
  valorItemHistorico: { fontSize: 14, fontWeight: '700', color: COLORS.onSurface },
  textoVazio: { fontSize: 14, color: COLORS.outline },

  // Rodapé de ações
  rodapeAcoes: {
    backgroundColor: COLORS.surface,
    marginHorizontal: -20,
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 18,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
  },
  botaoFecharConta: {
    backgroundColor: COLORS.secondary,
    paddingVertical: 15,
    borderRadius: 14,
    alignItems: 'center',
  },
  textoBotaoFecharConta: { color: COLORS.onSecondary, fontSize: 16, fontWeight: '700' },
});

export default styles;